"use strict";
/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["div[_ngcontent-%COMP%] {\r\n    h1 {\r\n      color: green;\r\n    }\r\n  }"];
exports.styles = styles;
//# sourceMappingURL=menu.component.scss.shim.ngstyle.js.map